### ISSUE TITLE
Persistent Database configuration file

### ISSUE THREAD

**Issue by kwent** [backstage/demo#50]
Hi,

Thanks for this repo, would be nice to have a configuration file for a persistent database as `postgresql` as well.

I find it very tricky to make it work (failed) with for heroku `hobby-dev` plan.

My configuration file:

```yaml
app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: https://backstage.acme.com

backend:
  baseUrl: https://backstage.acme.com
  listen:
    port:
      $env: PORT
      # The $PORT environment variable is a feature of Heroku
      # https://devcenter.heroku.com/articles/dynos#web-dynos
  database:
    client: pg
    usePluginSchemas: true,
    connection: ${DATABASE_URL}
    ssl: true
    plugin:
      auth:
        database: 
          $env: DATABASE_URL
      catalog:
        database:
          $env: DATABASE_URL

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'external' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
```

Resulting in
```text
2022-03-31T07:46:08.280406+00:00 app[web.1]: Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: no pg_hba.conf entry for host "3.218.227.138", user "foo", database "postgres", no encryption
```

Notice the database: "postgres", when it should be a different value. It's like the url parser doesn't extract the database name correctly.
